// The curated universe: well-known tickers, each mapped to offbeat public signals.
// polarity: +1 = a rise has historically been a tailwind for the company, -1 = a rise is a headwind,
// 0 = context only (direction is ambiguous for this company). These are hedged, educational framings.

const SRC = {
  fred: "FRED, Federal Reserve Bank of St. Louis",
  wiki: "Wikimedia pageviews API",
  pypi: "PyPI download stats (pypistats.org)",
  hn: "Hacker News (Algolia search API)",
  openfda: "openFDA (U.S. Food & Drug Administration)",
  nhtsa: "NHTSA complaints API",
  tsa: "TSA checkpoint travel numbers",
  greenhouse: "Company job board (Greenhouse public API)",
  sec: "SEC EDGAR XBRL data",
  eia: "U.S. Energy Information Administration (EIA)",
  lever: "Company job board (Lever public API)",
  npm: "npm download stats (api.npmjs.org)",
};

// ---- reusable signal builders ----
const fred = (series, o) => ({ source: "fred", params: { series }, sourceName: SRC.fred, ...o });
const wiki = (article, label, o) => ({
  source: "wiki", params: { article }, sourceName: SRC.wiki, unit: "views", compare: "recent", threshold: 8,
  metric: `Daily views of the English Wikipedia article “${label}”`,
  what: `How many people look up “${label}” on Wikipedia each day. It is a free, public stand-in for search interest: when curiosity spikes, pageviews usually spike too.`,
  ...o,
});
const pypi = (pkg, o) => ({
  source: "pypi", params: { pkg }, sourceName: SRC.pypi, unit: "downloads", compare: "recent", threshold: 5,
  metric: `Daily downloads of the “${pkg}” Python package`,
  ...o,
});
const hn = (query, o) => ({
  source: "hn", params: { query }, sourceName: SRC.hn, unit: "stories", compare: "recent", threshold: 15,
  metric: `Hacker News stories per week mentioning “${query}”`,
  what: `How often “${query}” shows up in stories posted to Hacker News, the news board many software engineers read. It is a rough gauge of developer chatter.`,
  ...o,
});
const tsa = (o) => ({
  source: "tsa", params: {}, sourceName: SRC.tsa, unit: "travelers", compare: "yoy7", threshold: 2,
  metric: "People screened at TSA airport checkpoints per day (7-day average vs the same week last year)",
  what: "The number of travelers passing through U.S. airport security every day, published by the TSA. It is one of the fastest public reads on how much Americans are traveling.",
  ...o,
});
const greenhouse = (board, name, o) => ({
  source: "greenhouse", params: { board }, sourceName: SRC.greenhouse, unit: "roles", compare: "snapshot", threshold: 5,
  metric: `Open roles listed on ${name}'s public job board`,
  what: `A count of the jobs ${name} is advertising right now on its public careers board. Companies tend to hire ahead of growth and freeze hiring ahead of slowdowns.`,
  ...o,
});
const lever = (company, name, o) => ({
  source: "lever", params: { company }, sourceName: SRC.lever, unit: "roles", compare: "snapshot", threshold: 5,
  metric: `Open roles listed on ${name}'s public job board`,
  what: `A count of the jobs ${name} is advertising right now on its public careers board. Companies tend to hire ahead of growth and freeze hiring ahead of slowdowns.`,
  ...o,
});
const npm = (pkg, o) => ({
  source: "npm", params: { pkg }, sourceName: SRC.npm, unit: "downloads", compare: "recent", threshold: 5,
  metric: `Daily downloads of the “${pkg}” JavaScript package`,
  ...o,
});
const inventory = (name, o) => ({
  source: "secInventory", params: {}, sourceName: SRC.sec, unit: "usdB", compare: "yoy", threshold: 10, polarity: -1,
  metric: `${name}'s reported inventory, from quarterly SEC filings`,
  what: `The dollar value of products ${name} has built or bought but not yet sold, as reported in its 10-Q and 10-K filings. It is the corporate version of a stockroom count.`,
  ...o,
});
const gas = (o) => fred("GASREGW", { unit: "usdGal", compare: "recent", threshold: 2, metric: "U.S. average regular gasoline price (weekly)", what: "The average price drivers pay for a gallon of regular gas across the U.S., surveyed weekly by the Energy Information Administration and published on FRED.", ...o });

export const TICKERS = [
  {
    ticker: "AAPL", name: "Apple", sector: "Consumer tech",
    news: '"Apple" (iPhone OR Mac OR iPad OR "Tim Cook")',
    signals: [
      wiki("IPhone", "iPhone", { id: "iphone-curiosity", name: "iPhone curiosity", polarity: 1,
        why: "iPhones are roughly half of Apple's revenue. Rising public curiosity about the iPhone often shows up around launches and upgrade waves, and a fade can hint at a quieter cycle.",
        up: "more people are curious about iPhones, which tends to come with upgrade interest", down: "interest in iPhones is cooling off compared with recent weeks" }),
      fred("MRTSSM443USS", { id: "electronics-stores", name: "Electronics store sales", unit: "usdM", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Monthly U.S. sales at electronics & appliance stores (Census, seasonally adjusted)",
        what: "How much Americans spend each month at electronics and appliance stores, from the Census Bureau's retail survey.",
        why: "Apple sells a lot of hardware through retailers. Store sales for gadgets are a broad read on whether shoppers are opening their wallets for electronics at all.",
        up: "shoppers are spending more on electronics than a year ago", down: "electronics spending is running below last year" }),
      inventory("Apple", { id: "apple-inventory", name: "Apple's stockroom",
        why: "Apple runs famously lean inventory. A jump in inventory can mean products are not selling as fast as planned, or that Apple is stocking up ahead of a launch, so it is a signal to watch rather than a verdict.",
        up: "Apple is holding more unsold product than a year ago", down: "Apple is holding less product than a year ago, consistent with lean, fast-selling inventory" }),
    ],
  },
  {
    ticker: "NVDA", name: "Nvidia", sector: "Semiconductors / AI",
    news: '"Nvidia"',
    signals: [
      pypi("torch", { id: "pytorch-installs", name: "AI builders installing PyTorch", polarity: 1,
        what: "How many times PyTorch, the most popular toolkit for building AI models, is downloaded each day. Most serious PyTorch work runs on Nvidia GPUs.",
        why: "Every developer installing PyTorch is someone building or running AI models, and most of that runs on Nvidia hardware. It is a grassroots read on AI activity, well upstream of data-center orders.",
        up: "more developers are pulling down AI tooling than a month ago", down: "AI tooling downloads have slowed versus the prior month" }),
      hn("nvidia", { id: "dev-chatter", name: "Developer chatter about Nvidia", polarity: 1,
        why: "Engineers talk about the chips they want and can't get. A rise in chatter often tracks product launches and demand; a slump can mean attention has moved elsewhere.",
        up: "engineers are talking about Nvidia more than usual", down: "developer chatter about Nvidia has quieted" }),
      inventory("Nvidia", { id: "nvidia-inventory", name: "Nvidia's stockroom",
        why: "Chipmakers build inventory before big product ramps, but a pile-up that outruns sales has preceded past chip gluts. Read it alongside demand signals.",
        up: "Nvidia is holding more inventory than a year ago (stocking up for demand, or chips waiting for buyers)", down: "Nvidia is holding less inventory than a year ago" }),
      fred("VIXCLS", { id: "vix-stress", scout: true, name: "Market stress (VIX)", unit: "index", compare: "recent", threshold: 8, polarity: -1,
        metric: "CBOE Volatility Index (VIX), weekly average vs the weeks before",
        what: "We pull the VIX — a free public score of how nervous the stock market feels. Higher = more fear.",
        why: "Nvidia is a high-flying growth stock. When fear rises, those names often get hit first. This is a risk-mood clue, not a read on chip demand.",
        up: "market stress is elevated versus recent weeks", down: "market stress has eased versus recent weeks" }),
    ],
  },
  {
    ticker: "MSFT", name: "Microsoft", sector: "Software / cloud",
    news: '"Microsoft" (Azure OR Copilot OR Windows OR Nadella)',
    signals: [
      pypi("azure-core", { id: "azure-sdk", name: "Developers wiring up Azure", polarity: 1,
        what: "Daily downloads of azure-core, the shared foundation of Microsoft's Azure Python SDKs. Software that talks to Azure installs it.",
        why: "Cloud is Microsoft's growth engine. More installs of the Azure SDK means more code being built and deployed against Azure, a ground-level hint of cloud usage.",
        up: "more code is being built against Azure than a month ago", down: "Azure SDK installs have dipped versus the prior month" }),
      wiki("Microsoft_Copilot", "Microsoft Copilot", { id: "copilot-curiosity", name: "Copilot curiosity", polarity: 1,
        why: "Copilot is Microsoft's big AI bet for Office and Windows. Public curiosity is an early read on whether the AI pitch is reaching regular users.",
        up: "public curiosity about Copilot is rising", down: "curiosity about Copilot is fading versus recent weeks" }),
      hn("copilot", { id: "copilot-chatter", name: "Developer chatter about Copilot", polarity: 1,
        why: "GitHub Copilot, owned by Microsoft, is one of the most-used AI coding tools. Engineers discussing it is a sign it stays relevant in a crowded field.",
        up: "developers are discussing Copilot more than usual", down: "developer chatter about Copilot has slowed" }),
    ],
  },
  {
    ticker: "TSLA", name: "Tesla", sector: "Autos / EVs",
    news: '"Tesla" (Musk OR electric OR "Model Y" OR Cybertruck)',
    signals: [
      { id: "modely-complaints", name: "Model Y owner complaints", source: "nhtsa", params: { make: "TESLA", model: "MODEL Y (ALL VARIANTS)", years: [2023, 2024, 2025, 2026] }, sourceName: SRC.nhtsa,
        unit: "complaints", compare: "recent", threshold: 15, polarity: -1,
        metric: "Owner complaints filed with NHTSA about 2023–2026 Model Ys, per month",
        what: "Complaints Model Y owners file with the National Highway Traffic Safety Administration, the federal auto-safety regulator. A surge is how many recalls and investigations start.",
        why: "The Model Y is Tesla's best-selling car. A rising complaint count can foreshadow recalls, investigations, and warranty costs. (More cars on the road also means more complaints, so sharp jumps matter more than slow drift.)",
        up: "complaints are climbing faster than the prior few months", down: "complaints have eased compared with the prior few months" },
      wiki("Tesla_Model_Y", "Tesla Model Y", { id: "modely-curiosity", name: "Model Y curiosity", polarity: 1,
        why: "Curiosity about Tesla's best-seller is a free proxy for shopping interest, ahead of the quarterly delivery numbers.",
        up: "more people are looking up the Model Y", down: "interest in the Model Y is cooling off" }),
      gas({ id: "gas-ev", name: "Pain at the pump", polarity: 1,
        why: "Expensive gas makes electric cars look like a better deal. High or rising gas prices have historically nudged more shoppers toward EVs.",
        up: "gas is getting pricier, which makes EVs look more attractive", down: "gas is getting cheaper, which weakens the money-saving pitch for EVs" }),
    ],
  },
  {
    ticker: "AMZN", name: "Amazon", sector: "E-commerce / cloud",
    news: '"Amazon" (AWS OR Prime OR Jassy OR retail)',
    signals: [
      fred("PCU322211322211", { id: "cardboard", name: "Cardboard box prices", unit: "index", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Producer price index for corrugated & solid fiber boxes (monthly)",
        what: "What box makers charge for corrugated cardboard boxes, tracked by the Bureau of Labor Statistics. When demand for boxes is strong, box makers can raise prices.",
        why: "Almost every Amazon order ships in a box. Firm box prices hint at healthy shipping volume across e-commerce; slumping prices can mean fewer packages moving.",
        up: "box prices are up from a year ago, a hint of firm demand for shipping boxes", down: "box prices are below last year, a hint of softer package volume" }),
      fred("IPN32213N", { id: "paperboard", name: "U.S. paperboard production", unit: "index", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Industrial production index for paperboard mills (monthly, Federal Reserve)",
        what: "How much paperboard U.S. mills are producing — the raw material behind corrugated boxes and much of the cardboard packaging stream. A free public stand-in for the 'recycling / packaging volumes → goods demand' idea (city e-waste tonnage is only published yearly).",
        why: "More paperboard usually means more boxes being made for goods moving through warehouses and e-commerce. Soft production can mean fewer packages in the system.",
        up: "mills are producing more paperboard than a year ago", down: "paperboard production is below a year ago" }),
      fred("RSNSR", { id: "online-sales", name: "Online store sales", unit: "usdM", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Monthly U.S. sales at nonstore retailers (mostly online), Census",
        what: "Monthly sales at 'nonstore retailers', the Census category that is mostly online shopping.",
        why: "Amazon is the biggest player in U.S. online retail, so the whole category growing is a rising tide for it.",
        up: "online sales are growing versus last year", down: "online sales are running below last year" }),
      pypi("boto3", { id: "aws-sdk", name: "Developers wiring up AWS", polarity: 1,
        what: "Daily downloads of boto3, the official Python toolkit for Amazon Web Services. Almost any Python code that touches AWS installs it.",
        why: "AWS earns most of Amazon's profit. More boto3 installs means more software being built and deployed on AWS.",
        up: "more code is being deployed against AWS than a month ago", down: "AWS toolkit installs have dipped versus the prior month" }),
    ],
  },
  {
    ticker: "WMT", name: "Walmart", sector: "Retail",
    news: '"Walmart"',
    signals: [
      fred("APU0000708111", { id: "egg-prices", name: "Egg prices", unit: "usdDozen", compare: "yoy", threshold: 5, polarity: 1,
        metric: "Average U.S. price of a dozen large Grade A eggs (BLS, monthly)",
        what: "What a dozen eggs costs at the store on average, from the Bureau of Labor Statistics. Eggs are a famously visible grocery price.",
        why: "When grocery bills jump, shoppers have historically traded down to discount grocers, and Walmart is the biggest one. Pricier eggs can mean more trips to Walmart, though it also squeezes margins.",
        up: "grocery staples are pricier than a year ago, which tends to push shoppers toward discounters", down: "grocery staples are cheaper than a year ago, easing the pressure to trade down" }),
      gas({ id: "gas-wallet", name: "Gas squeeze on shoppers", polarity: -1,
        why: "Walmart's core shoppers drive to the store and feel gas prices directly. Every extra dollar at the pump is a dollar not spent in the aisles.",
        up: "gas is getting pricier, leaving shoppers less to spend", down: "gas is getting cheaper, leaving shoppers a little more to spend" }),
      fred("ICSA", { id: "jobless-claims", name: "New jobless claims", unit: "claims", compare: "recent", threshold: 5, polarity: 0,
        metric: "Initial unemployment claims filed per week (Dept. of Labor)",
        what: "How many people file for unemployment benefits for the first time each week, the most up-to-date public read on layoffs.",
        why: "Rising layoffs squeeze spending, but Walmart has historically held up better than most retailers in downturns because shoppers trade down. That is why we treat this one as context rather than good or bad.",
        up: "layoffs are ticking up", down: "layoffs are easing" }),
    ],
  },
  {
    ticker: "DAL", name: "Delta Air Lines", sector: "Airlines", hn: "Delta airline", hnMust: "\\bDelta\\b",
    news: '"Delta Air Lines"',
    signals: [
      tsa({ id: "tsa-dal", name: "Airport security lines", polarity: 1,
        why: "More people in TSA lines means fuller planes. Airlines report quarterly, but TSA posts numbers every day, so this is a near real-time read on air-travel demand.",
        up: "more people are flying than this time last year", down: "fewer people are flying than this time last year" }),
      fred("DJFUELUSGULF", { id: "jet-fuel", name: "Jet fuel price", unit: "usdGal", compare: "recent", threshold: 3, polarity: -1,
        metric: "U.S. Gulf Coast kerosene-type jet fuel spot price (daily)",
        what: "The wholesale price of jet fuel on the U.S. Gulf Coast, published by the EIA via FRED.",
        why: "Fuel is one of an airline's biggest costs, often a quarter of expenses. Rising jet fuel eats directly into profit unless fares rise too.",
        up: "jet fuel is getting more expensive, a cost headwind", down: "jet fuel is getting cheaper, a cost tailwind" }),
    ],
  },
  {
    ticker: "UNP", name: "Union Pacific", sector: "Railroads",
    news: '"Union Pacific"',
    signals: [
      fred("RAILFRTCARLOADSD11", { id: "rail-carloads", name: "Rail carloads", unit: "carloads", compare: "yoy", threshold: 2, polarity: 1,
        metric: "U.S. rail freight carloads per month (seasonally adjusted, BTS)",
        what: "How many freight carloads U.S. railroads move each month, from the Bureau of Transportation Statistics.",
        why: "Railroads get paid by the load. Carloads are close to a direct read on Union Pacific's business volume, published well before earnings.",
        up: "railroads are hauling more than a year ago", down: "railroads are hauling less than a year ago" }),
      fred("TRUCKD11", { id: "truck-tonnage", name: "Truck tonnage", unit: "index", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Truck tonnage index (monthly, seasonally adjusted, BTS)",
        what: "An index of how much freight trucks haul, from the Bureau of Transportation Statistics. It is a broad gauge of goods moving through the economy.",
        why: "Trucks and trains move the same economy. When trucking volume rises, there is usually more freight for railroads too.",
        up: "the freight economy is busier than a year ago", down: "the freight economy is slower than a year ago" }),
      fred("PERMIT", { id: "building-permits", scout: true, name: "Building permits", unit: "thousandUnits", compare: "yoy", threshold: 3, polarity: 1,
        metric: "U.S. building permits for new private housing (monthly, Census)",
        what: "We pull U.S. building permits — how many new homes builders are cleared to start. It is an early housing-activity clue.",
        why: "New homes need lumber, appliances, and materials that often travel by rail. More permits can mean more freight for Union Pacific later; fewer permits can mean less.",
        up: "builders are permitting more homes than a year ago", down: "builders are permitting fewer homes than a year ago" }),
    ],
  },
  {
    ticker: "LLY", name: "Eli Lilly", hnMust: "Lilly|Zepbound|Mounjaro|tirzepatide", sector: "Pharma",
    news: '("Eli Lilly" OR Zepbound OR Mounjaro)',
    signals: [
      { id: "tirzepatide-reports", name: "Mounjaro/Zepbound usage footprint", source: "openfda", params: { generic: "tirzepatide" }, sourceName: SRC.openfda,
        unit: "reports", compare: "yoy", threshold: 10, polarity: 1,
        metric: "Monthly FDA adverse-event reports that mention tirzepatide (Mounjaro, Zepbound)",
        what: "Reports of side effects filed with the FDA that mention tirzepatide, Lilly's blockbuster weight-loss and diabetes drug. Report counts tend to grow with the number of people taking a drug.",
        why: "More patients means more reports, so the trend is a rough, unusual proxy for how fast use is growing. Caveat: a spike can also mean a real safety concern, so this is a signal to read carefully.",
        up: "the drug's footprint is growing versus a year ago", down: "report volume is below a year ago" },
      wiki("Tirzepatide", "Tirzepatide", { id: "tirzepatide-curiosity", name: "Tirzepatide curiosity", polarity: 1,
        why: "Public curiosity about Lilly's weight-loss drug is an early read on patient demand, before prescription data shows up in earnings.",
        up: "curiosity about tirzepatide is rising", down: "curiosity about tirzepatide is cooling off" }),
    ],
  },
  {
    ticker: "NVO", name: "Novo Nordisk", hn: "Ozempic", hnMust: "Novo|Ozempic|Wegovy|semaglutide", sector: "Pharma",
    news: '("Novo Nordisk" OR Wegovy OR Ozempic)',
    signals: [
      { id: "semaglutide-reports", name: "Ozempic/Wegovy usage footprint", source: "openfda", params: { generic: "semaglutide" }, sourceName: SRC.openfda,
        unit: "reports", compare: "yoy", threshold: 10, polarity: 1,
        metric: "Monthly FDA adverse-event reports that mention semaglutide (Ozempic, Wegovy)",
        what: "Reports of side effects filed with the FDA that mention semaglutide, Novo's blockbuster drug. Report counts tend to grow with the number of people taking a drug.",
        why: "More patients means more reports, so the trend is a rough proxy for how fast use is growing in the U.S. Caveat: a spike can also flag a real safety issue.",
        up: "the drug's footprint is growing versus a year ago", down: "report volume is below a year ago" },
      wiki("Semaglutide", "Semaglutide", { id: "semaglutide-curiosity", name: "Semaglutide curiosity", polarity: 1,
        why: "Public curiosity about Ozempic's active ingredient is an early read on patient demand.",
        up: "curiosity about semaglutide is rising", down: "curiosity about semaglutide is cooling off" }),
      wiki("Tirzepatide", "Tirzepatide", { id: "rival-curiosity", name: "Rival drug buzz", polarity: -1,
        why: "Tirzepatide is Eli Lilly's competing drug. When curiosity about the rival rises, it can signal patients and doctors shifting attention away from Novo.",
        up: "the rival drug is drawing more attention", down: "attention on the rival drug is cooling" }),
    ],
  },
  {
    ticker: "HD", name: "Home Depot", sector: "Home improvement",
    news: '"Home Depot"',
    signals: [
      fred("HOUST", { id: "housing-starts", name: "New homes breaking ground", unit: "thousandUnits", compare: "yoy", threshold: 3, polarity: 1,
        metric: "New privately-owned housing units started (annualized, monthly, Census)",
        what: "How many new homes builders started constructing, from the Census Bureau. Every new home needs lumber, fixtures, and appliances.",
        why: "Builders and pros are a big slice of Home Depot's sales, and new homeowners spend heavily on improvements. More starts means more demand down the line.",
        up: "builders are breaking ground on more homes than a year ago", down: "builders are starting fewer homes than a year ago" }),
      fred("MORTGAGE30US", { id: "mortgage-rates", name: "Mortgage rates", unit: "pct", compare: "recent", threshold: 2, polarity: -1,
        metric: "Average 30-year fixed mortgage rate (Freddie Mac, weekly)",
        what: "The average rate on a 30-year fixed mortgage, surveyed weekly by Freddie Mac.",
        why: "People renovate when they buy, sell, or refinance. High mortgage rates freeze the housing market, and with it a lot of big-ticket home projects.",
        up: "mortgages are getting pricier, which tends to freeze home projects", down: "mortgage rates are easing, which can thaw housing activity" }),
      fred("WPU081", { id: "lumber", name: "Lumber prices", unit: "index", compare: "yoy", threshold: 3, polarity: 0,
        metric: "Producer price index for lumber (monthly, BLS)",
        what: "What lumber mills charge for wood, tracked by the Bureau of Labor Statistics.",
        why: "Pricier lumber raises the dollar value of each sale, but it can also price out DIY projects. That is why we treat it as context rather than good or bad.",
        up: "lumber is pricier than a year ago", down: "lumber is cheaper than a year ago" }),
    ],
  },
  {
    ticker: "MCD", name: "McDonald's", hnMust: "McDonald", sector: "Restaurants",
    news: '"McDonald\'s"',
    signals: [
      fred("APU0000703112", { id: "beef", name: "Ground beef prices", unit: "usdLb", compare: "yoy", threshold: 4, polarity: -1,
        metric: "Average U.S. price of 100% ground beef per pound (BLS, monthly)",
        what: "What a pound of ground beef costs at retail, from the Bureau of Labor Statistics.",
        why: "Beef is the core of the menu. Rising beef costs squeeze margins for McDonald's and its franchisees unless they raise prices.",
        up: "beef is pricier than a year ago, a cost headwind", down: "beef is cheaper than a year ago, a cost tailwind" }),
      fred("CUSR0000SEFV", { id: "eating-out", name: "Price of eating out", unit: "index", compare: "yoy", threshold: 3, polarity: 0,
        metric: "Consumer price index for food away from home (monthly, BLS)",
        what: "How fast restaurant prices are rising across the U.S., from the consumer price index.",
        why: "Rising menu prices lift revenue per order, but when eating out gets too expensive, budget diners cut back. That is why we treat it as context.",
        up: "restaurant prices are rising faster", down: "restaurant price growth is slowing" }),
      fred("APU0000708111", { id: "eggs-breakfast", name: "Egg prices (breakfast costs)", unit: "usdDozen", compare: "yoy", threshold: 5, polarity: -1,
        metric: "Average U.S. price of a dozen large Grade A eggs (BLS, monthly)",
        what: "What a dozen eggs costs on average, from the Bureau of Labor Statistics.",
        why: "Breakfast is a big, high-margin daypart, and the Egg McMuffin runs on eggs. Egg spikes have squeezed restaurant costs before.",
        up: "eggs are pricier than a year ago, a breakfast cost headwind", down: "eggs are cheaper than a year ago, easing breakfast costs" }),
    ],
  },
  {
    ticker: "XOM", name: "ExxonMobil", sector: "Energy", hn: "Exxon", hnMust: "\\bExxon",
    news: '("ExxonMobil" OR "Exxon Mobil")',
    signals: [
      fred("DCOILWTICO", { id: "wti", name: "Crude oil price", unit: "usdBbl", compare: "recent", threshold: 3, polarity: 1,
        metric: "WTI crude oil spot price (daily, EIA)",
        what: "The price of a barrel of West Texas Intermediate crude, the U.S. oil benchmark.",
        why: "Exxon pumps millions of barrels a day. Every dollar move in oil flows fairly directly into its profit.",
        up: "oil is getting more expensive, which lifts producer profits", down: "oil is getting cheaper, which trims producer profits" }),
      { id: "crude-stocks", name: "U.S. crude oil in storage", source: "eiaWeeklyXls", params: { series: "WCESTUS1" }, sourceName: SRC.eia,
        unit: "kbbl", compare: "recent", threshold: 1.5, polarity: -1,
        metric: "Weekly U.S. ending stocks of crude oil excluding the Strategic Petroleum Reserve (thousand barrels)",
        what: "How many barrels of commercial crude sit in U.S. tanks, pipelines, and storage — the same inventory idea hedge funds chase with 'fuel storage from satellites,' published weekly for free by the EIA.",
        why: "Building inventories usually mean more supply than the market is absorbing, which has historically weighed on oil prices and producer profits. Drawing inventories is the opposite.",
        up: "commercial crude stocks are building versus the prior weeks", down: "commercial crude stocks are being drawn down versus the prior weeks" },
      gas({ id: "gas-refining", name: "Gas pump prices", polarity: 1,
        why: "Exxon is also one of the biggest refiners. Firm gasoline prices usually go with healthy refining margins.",
        up: "gas prices are firming", down: "gas prices are easing" }),
    ],
  },
  {
    ticker: "COIN", name: "Coinbase", sector: "Crypto / fintech",
    news: '"Coinbase"',
    signals: [
      fred("CBBTCUSD", { id: "bitcoin", name: "Bitcoin price", unit: "usd", compare: "recent", threshold: 5, polarity: 1,
        metric: "Bitcoin price on Coinbase (daily, via FRED)",
        what: "The price of one bitcoin on Coinbase's exchange, as recorded daily by FRED.",
        why: "Coinbase earns most of its money from trading fees, and trading surges when crypto prices run.",
        up: "bitcoin is climbing, which usually brings traders back", down: "bitcoin is sliding, which usually cools trading" }),
      wiki("Bitcoin", "Bitcoin", { id: "bitcoin-curiosity", name: "Bitcoin curiosity", polarity: 1,
        why: "Retail curiosity tends to rise before new people open exchange accounts. It is a crowd-mood gauge for crypto.",
        up: "regular people are getting curious about bitcoin again", down: "public curiosity about bitcoin is fading" }),
      greenhouse("coinbase", "Coinbase", { id: "coinbase-hiring", name: "Coinbase hiring", polarity: 1,
        why: "Crypto companies hire aggressively in boom times and cut hard in busts. The hiring board is a window into how management sees the road ahead.",
        up: "Coinbase is advertising more roles than at our earlier snapshots", down: "Coinbase is advertising fewer roles than at our earlier snapshots" }),
    ],
  },
  {
    ticker: "ABNB", name: "Airbnb", sector: "Travel",
    news: '"Airbnb"',
    signals: [
      tsa({ id: "tsa-abnb", name: "Airport security lines", polarity: 1,
        why: "Many Airbnb stays start with a flight. Daily TSA counts are a near real-time read on travel demand.",
        up: "more people are traveling than this time last year", down: "fewer people are traveling than this time last year" }),
      fred("CUSR0000SEHB", { id: "lodging-prices", name: "Hotel & lodging prices", unit: "index", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Consumer price index for lodging away from home (monthly, BLS)",
        what: "How fast prices for hotels and other short-term lodging are rising, from the consumer price index.",
        why: "When hotels get pricier, travelers look for alternatives and hosts can charge more. Firm lodging prices are usually good for Airbnb's take.",
        up: "lodging prices are rising, a sign of firm travel demand", down: "lodging prices are softening" }),
      greenhouse("airbnb", "Airbnb", { id: "airbnb-hiring", name: "Airbnb hiring", polarity: 1,
        why: "Hiring is a forward-looking budget decision. A growing jobs board suggests management expects growth.",
        up: "Airbnb is advertising more roles than at our earlier snapshots", down: "Airbnb is advertising fewer roles than at our earlier snapshots" }),
      fred("UNRATE", { id: "unemployment", scout: true, name: "U.S. unemployment rate", unit: "pct", compare: "recent", threshold: 3, polarity: -1,
        metric: "U.S. civilian unemployment rate (monthly, BLS)",
        what: "We pull the U.S. unemployment rate — the share of people who want a job but do not have one.",
        why: "Airbnb stays are a want, not a need. When more people lose jobs, travel budgets usually shrink. Lower unemployment can support bookings; higher unemployment can lean against them.",
        up: "the unemployment rate is rising versus recent months", down: "the unemployment rate is easing versus recent months" }),
    ],
  },
  {
    ticker: "DIS", name: "Disney", sector: "Media / parks",
    news: '"Disney" (parks OR Iger OR "box office" OR streaming)',
    signals: [
      wiki("Walt_Disney_World", "Walt Disney World", { id: "wdw-curiosity", name: "Disney World trip planning", polarity: 1,
        why: "Parks and experiences are Disney's biggest profit engine. People research a trip before they book, so curiosity about Disney World is an early demand hint.",
        up: "more people are researching Disney World", down: "interest in Disney World is cooling off" }),
      tsa({ id: "tsa-dis", name: "Airport security lines", polarity: 1,
        why: "Many park visitors fly in. Daily TSA counts are a near real-time read on travel demand.",
        up: "more people are flying than this time last year", down: "fewer people are flying than this time last year" }),
      fred("UMCSENT", { id: "sentiment", name: "Consumer mood", unit: "index", compare: "yoy", threshold: 4, polarity: 1,
        metric: "University of Michigan consumer sentiment index (monthly)",
        what: "A monthly survey of how upbeat Americans feel about their finances and the economy.",
        why: "A Disney vacation is a big discretionary purchase. Families book them when they feel good about money.",
        up: "Americans are feeling better about money than a year ago", down: "Americans are gloomier about money than a year ago" }),
    ],
  },
  {
    ticker: "F", name: "Ford", sector: "Autos",
    news: '("Ford Motor" OR "Ford F-150")',
    signals: [
      { id: "f150-complaints", name: "F-150 owner complaints", source: "nhtsa", params: { make: "FORD", model: "F-150 (SUPER CREW) GAS", years: [2023, 2024, 2025, 2026] }, sourceName: SRC.nhtsa,
        unit: "complaints", compare: "recent", threshold: 15, polarity: -1,
        metric: "Owner complaints filed with NHTSA about 2023–2026 F-150 SuperCrew (gas), per month",
        what: "Complaints F-150 owners file with the National Highway Traffic Safety Administration. Complaint surges are how many recalls and investigations start.",
        why: "The F-Series is Ford's profit machine, and Ford has led the industry in recalls. Rising complaints can foreshadow recall and warranty costs.",
        up: "complaints are climbing versus the prior few months", down: "complaints have eased versus the prior few months" },
      fred("TOTALSA", { id: "vehicle-sales", name: "U.S. vehicle sales pace", unit: "millionUnits", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Total U.S. light vehicle sales, annualized (monthly, BEA)",
        what: "How many new cars and light trucks Americans are buying, as an annual pace.",
        why: "A rising tide for the whole industry. Ford's U.S. sales tend to move with the market.",
        up: "Americans are buying cars at a faster pace than a year ago", down: "car buying is slower than a year ago" }),
      gas({ id: "gas-trucks", name: "Gas prices vs. trucks", polarity: -1,
        why: "Ford's lineup leans on big trucks and SUVs. Expensive gas has historically pushed shoppers toward smaller, thriftier vehicles.",
        up: "gas is getting pricier, a headwind for big trucks", down: "gas is getting cheaper, which helps truck demand" }),
      fred("BAMLH0A0HYM2", { id: "hy-spread", scout: true, name: "Junk-bond stress", unit: "pct", compare: "recent", threshold: 5, polarity: -1,
        metric: "ICE BofA U.S. high-yield option-adjusted spread (daily → compared recent)",
        what: "We pull the junk-bond spread — how much extra interest lenders demand for riskier companies. Wider = credit markets are nervous.",
        why: "Many car buyers use loans. When credit gets tight, auto sales and financing get harder. Wider spreads can lean against Ford; tighter spreads can lean with it.",
        up: "credit stress is rising (junk spreads are wider)", down: "credit stress is easing (junk spreads are tighter)" }),
    ],
  },
  // ---- Batch 2 (Oct 2026): popular names with solid free public data ----
  {
    ticker: "GOOGL", name: "Alphabet (Google)", sector: "Search / cloud / AI", hn: "Google", hnMust: "\\bGoogle\\b|Alphabet|Gemini|Waymo|YouTube",
    news: '("Alphabet" OR "Google") (Gemini OR Pichai OR "Google Cloud" OR search)',
    signals: [
      pypi("google-genai", { id: "gemini-sdk", name: "Developers building on Gemini", polarity: 1,
        what: "Daily downloads of google-genai, Google's official Python toolkit for its Gemini AI models. Code that calls Gemini installs it.",
        why: "Google is racing to turn Gemini into a business through its cloud. More installs means more developers wiring Gemini into real apps, a ground-level read on AI adoption well before cloud revenue is reported.",
        up: "more developers are building on Gemini than a month ago", down: "Gemini toolkit installs have dipped versus the prior month" }),
      pypi("google-cloud-storage", { id: "gcp-sdk", name: "Developers wiring up Google Cloud", polarity: 1,
        what: "Daily downloads of google-cloud-storage, the Python toolkit for storing files on Google Cloud. It is one of the most common building blocks of software that runs on Google Cloud.",
        why: "Google Cloud is Alphabet's fastest-growing big business. More installs of its storage toolkit means more code being deployed on it.",
        up: "more code is being built against Google Cloud than a month ago", down: "Google Cloud toolkit installs have dipped versus the prior month" }),
      wiki("Google_Gemini", "Google Gemini", { id: "gemini-curiosity", name: "Gemini curiosity", polarity: 1,
        why: "Gemini is Google's answer to ChatGPT and the AI layer inside Search. Rising public curiosity is a free read on whether regular people are noticing it.",
        up: "public curiosity about Gemini is rising", down: "curiosity about Gemini is fading versus recent weeks" }),
    ],
  },
  {
    ticker: "META", name: "Meta Platforms", sector: "Social media / ads", hn: "Meta", hnMust: "\\bMeta\\b|Facebook|Instagram|Zuckerberg|WhatsApp",
    news: '("Meta Platforms" OR Zuckerberg OR Instagram)',
    signals: [
      fred("RSNSR", { id: "online-sales", name: "Online store sales (Meta's big advertisers)", unit: "usdM", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Monthly U.S. sales at nonstore retailers (mostly online), Census",
        what: "Monthly sales at 'nonstore retailers', the Census category that is mostly online shopping.",
        why: "Online stores are some of Meta's biggest advertisers: they find shoppers through Instagram and Facebook ads. When online sales grow, ad budgets usually grow with them.",
        up: "online sales are growing versus last year, which tends to keep ad budgets healthy", down: "online sales are running below last year, which can squeeze ad budgets" }),
      wiki("Instagram", "Instagram", { id: "instagram-curiosity", name: "Instagram curiosity", polarity: 1,
        why: "Instagram is Meta's biggest ad engine after Facebook itself. Public curiosity rises with new features and cultural moments and fades when attention moves to rivals.",
        up: "more people are looking up Instagram than in recent weeks", down: "interest in Instagram is cooling off" }),
      wiki("Threads_(social_network)", "Threads", { id: "threads-curiosity", name: "Threads curiosity", polarity: 1,
        why: "Threads is Meta's newest app, its bid to take X/Twitter's place. Curiosity is an early read on whether it's still pulling in new people, before Meta reports user numbers.",
        up: "curiosity about Threads is rising", down: "curiosity about Threads is fading versus recent weeks" }),
    ],
  },
  {
    ticker: "NFLX", name: "Netflix", sector: "Streaming",
    news: '"Netflix"',
    signals: [
      wiki("Netflix", "Netflix", { id: "netflix-curiosity", name: "Netflix curiosity", polarity: 1,
        why: "Big hit shows and live events send people to look up Netflix. Spikes often line up with buzzy releases; a long fade can mean a quieter content slate.",
        up: "more people are looking up Netflix than in recent weeks", down: "interest in Netflix is cooling off" }),
      fred("CUSR0000SERA02", { id: "streaming-prices", name: "Streaming & TV subscription prices", unit: "index", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Consumer price index for cable, satellite, and live-streaming TV service (monthly, BLS)",
        what: "How fast the price of TV and streaming subscriptions is rising, from the government's consumer price index.",
        why: "Netflix has raised prices several times while still adding subscribers. When TV and streaming prices keep climbing across the industry, it suggests services still have pricing power; falling prices would point to a discount war.",
        up: "TV and streaming prices are higher than a year ago, a sign of pricing power", down: "TV and streaming prices are lower than a year ago, a sign of discounting" }),
    ],
  },
  {
    ticker: "COST", name: "Costco", sector: "Warehouse retail",
    news: '"Costco"',
    signals: [
      fred("MRTSSM452USS", { id: "general-merch", name: "General merchandise store sales", unit: "usdM", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Monthly U.S. sales at general merchandise stores, incl. warehouse clubs (Census, seasonally adjusted)",
        what: "How much Americans spend each month at big-box general stores, the Census category that includes warehouse clubs like Costco.",
        why: "Costco sits in this category, so its growth is a rough read on the aisles Costco competes in, published weeks before Costco's own sales report.",
        up: "big-box store sales are growing versus last year", down: "big-box store sales are running below last year" }),
      fred("APU0000708111", { id: "egg-prices", name: "Egg prices (bulk-buying pressure)", unit: "usdDozen", compare: "yoy", threshold: 5, polarity: 1,
        metric: "Average U.S. price of a dozen large Grade A eggs (BLS, monthly)",
        what: "What a dozen eggs costs at the store on average, from the Bureau of Labor Statistics. Eggs are a famously visible grocery price.",
        why: "When grocery bills jump, more shoppers buy in bulk to save money, and Costco's membership pitch gets easier to sell. Costco famously kept its egg prices low during past spikes.",
        up: "grocery staples are pricier than a year ago, which tends to push shoppers toward bulk buying", down: "grocery staples are cheaper than a year ago, easing the pressure to buy in bulk" }),
      inventory("Costco", { id: "costco-inventory", name: "Costco's stockroom",
        why: "Costco's inventory grows naturally as it opens warehouses, so only big jumps matter. A pile-up faster than sales can mean goods aren't moving and markdowns may follow.",
        up: "Costco is holding notably more merchandise than a year ago", down: "Costco is holding less merchandise than a year ago, consistent with fast-moving shelves" }),
    ],
  },
  {
    ticker: "NKE", name: "Nike", sector: "Apparel / footwear", hnMust: "\\bNike\\b",
    news: '"Nike"',
    signals: [
      inventory("Nike", { id: "nike-inventory", name: "Nike's stockroom", params: { concept: "InventoryFinishedGoodsNetOfReserves" },
        metric: "Nike's reported inventory of finished goods, from quarterly SEC filings",
        why: "In 2022 Nike's warehouses overflowed and it had to discount heavily, which hurt profits. Inventory growing faster than sales is the classic warning sign; shrinking inventory means the shoes are selling.",
        up: "Nike is holding more unsold product than a year ago", down: "Nike is holding less product than a year ago, which usually means fewer markdowns" }),
      fred("MRTSSM448USS", { id: "clothing-stores", name: "Clothing store sales", unit: "usdM", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Monthly U.S. sales at clothing & accessory stores (Census, seasonally adjusted)",
        what: "How much Americans spend each month at clothing and accessory stores, from the Census Bureau's retail survey.",
        why: "Many Nike sneakers and clothes are sold through stores like these. When shoppers spend more on apparel, there is more room for Nike to sell at full price.",
        up: "shoppers are spending more on clothes than a year ago", down: "clothing spending is running below last year" }),
      fred("CUSR0000SEAE", { id: "footwear-prices", name: "Shoe prices", unit: "index", compare: "yoy", threshold: 1.5, polarity: 1,
        metric: "Consumer price index for footwear (monthly, BLS)",
        what: "How fast shoe prices are changing in stores across the U.S., from the government's consumer price index.",
        why: "Rising shoe prices mean brands can charge more; falling shoe prices usually mean discounting to clear stock, which is what squeezed Nike's margins.",
        up: "shoe prices are higher than a year ago, a sign brands have pricing power", down: "shoe prices are lower than a year ago, a sign of discounting" }),
    ],
  },
  {
    ticker: "SBUX", name: "Starbucks", sector: "Restaurants / coffee",
    news: '"Starbucks"',
    signals: [
      fred("PCOFFOTMUSDM", { id: "coffee-beans", name: "Coffee bean prices", unit: "centsLb", compare: "yoy", threshold: 5, polarity: -1,
        metric: "Global price of mild arabica coffee beans (monthly, IMF via FRED)",
        what: "What roasters pay for arabica coffee beans, the kind Starbucks buys, tracked monthly by the International Monetary Fund.",
        why: "Beans are Starbucks' signature cost. Starbucks hedges months ahead, so spikes hit margins with a delay, but a big, lasting jump eventually shows up in costs or menu prices.",
        up: "coffee beans are pricier than a year ago, a cost headwind", down: "coffee beans are cheaper than a year ago, a cost tailwind" }),
      fred("APU0000709112", { id: "milk", name: "Milk prices", unit: "usdGal", compare: "yoy", threshold: 4, polarity: -1,
        metric: "Average U.S. price of a gallon of whole milk (BLS, monthly)",
        what: "What a gallon of whole milk costs at the store on average, from the Bureau of Labor Statistics.",
        why: "Lattes and other milk drinks are a big share of Starbucks orders. Pricier dairy raises the cost of almost every drink.",
        up: "milk is pricier than a year ago, a cost headwind", down: "milk is cheaper than a year ago, a cost tailwind" }),
      fred("MRTSSM722USS", { id: "restaurant-sales", name: "Restaurant & cafe sales", unit: "usdM", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Monthly U.S. sales at food services & drinking places (Census, seasonally adjusted)",
        what: "How much Americans spend each month at restaurants, cafes, and bars, from the Census Bureau's retail survey.",
        why: "A $6 latte is an easy treat to skip. When eating-out spending grows, it suggests people still have room for small luxuries.",
        up: "Americans are spending more at restaurants and cafes than a year ago", down: "eating-out spending is running below last year" }),
    ],
  },
  {
    ticker: "CMG", name: "Chipotle", sector: "Restaurants", hnMust: "Chipotle",
    news: '"Chipotle"',
    signals: [
      fred("APU0000703112", { id: "beef", name: "Ground beef prices", unit: "usdLb", compare: "yoy", threshold: 4, polarity: -1,
        metric: "Average U.S. price of 100% ground beef per pound (BLS, monthly)",
        what: "What a pound of ground beef costs at retail, from the Bureau of Labor Statistics. It is a public stand-in for what Chipotle pays for steak and barbacoa.",
        why: "Beef is one of Chipotle's biggest food costs. Chipotle has said rising beef prices pressure its margins unless it raises menu prices.",
        up: "beef is pricier than a year ago, a cost headwind", down: "beef is cheaper than a year ago, a cost tailwind" }),
      fred("APU0000706111", { id: "chicken", name: "Chicken prices", unit: "usdLb", compare: "yoy", threshold: 4, polarity: -1,
        metric: "Average U.S. price of a whole fresh chicken per pound (BLS, monthly)",
        what: "What a pound of whole chicken costs at the store on average, from the Bureau of Labor Statistics.",
        why: "Chicken is Chipotle's most-ordered protein. When chicken gets pricier, every burrito bowl costs more to make.",
        up: "chicken is pricier than a year ago, a cost headwind", down: "chicken is cheaper than a year ago, a cost tailwind" }),
      fred("MRTSSM722USS", { id: "restaurant-sales", name: "Restaurant sales", unit: "usdM", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Monthly U.S. sales at food services & drinking places (Census, seasonally adjusted)",
        what: "How much Americans spend each month at restaurants, cafes, and bars, from the Census Bureau's retail survey.",
        why: "Chipotle depends on people choosing to eat out. Growing restaurant spending is a rising tide; a slowdown means diners are cutting back.",
        up: "Americans are spending more at restaurants than a year ago", down: "eating-out spending is running below last year" }),
    ],
  },
  {
    ticker: "UBER", name: "Uber", sector: "Rides / delivery",
    news: '"Uber" (rides OR drivers OR Khosrowshahi OR "Uber Eats")',
    signals: [
      tsa({ id: "tsa-uber", name: "Airport security lines (airport rides)", polarity: 1,
        why: "Airport trips are among Uber's longest, priciest rides. More people flying usually means more rides to and from the airport.",
        up: "more people are flying than this time last year, which means more airport rides", down: "fewer people are flying than this time last year" }),
      fred("MRTSSM722USS", { id: "restaurant-sales", name: "Restaurant sales (Uber Eats)", unit: "usdM", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Monthly U.S. sales at food services & drinking places (Census, seasonally adjusted)",
        what: "How much Americans spend each month at restaurants, cafes, and bars, from the Census Bureau's retail survey.",
        why: "Uber Eats delivers restaurant food. More restaurant spending means a bigger pie for delivery orders.",
        up: "restaurant spending is growing versus last year", down: "restaurant spending is running below last year" }),
      gas({ id: "gas-drivers", name: "Gas prices (driver costs)", polarity: -1,
        why: "Uber's drivers pay for their own gas. When gas gets expensive, fewer drivers go online, rides get pricier, and Uber has added fuel surcharges in the past.",
        up: "gas is getting pricier, squeezing drivers", down: "gas is getting cheaper, which helps keep drivers on the road" }),
      wiki("Waymo", "Waymo", { id: "waymo-curiosity", name: "Robotaxi buzz (Waymo)", polarity: 0,
        why: "Waymo's driverless cars are both a partner (you can hail some through the Uber app) and a long-run threat to Uber's driver network. That is why we show this as context, not good or bad.",
        up: "curiosity about robotaxis is rising", down: "curiosity about robotaxis is cooling off" }),
    ],
  },
  {
    ticker: "AMD", name: "AMD", sector: "Semiconductors", hnMust: "\\bAMD\\b|Ryzen|Radeon|Instinct",
    news: '("Advanced Micro Devices" OR "AMD") (chip OR Ryzen OR Instinct OR "Lisa Su")',
    signals: [
      fred("IPB53122S", { id: "chip-output", name: "U.S. chip production", unit: "index", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Industrial production index for semiconductors and related parts (monthly, Federal Reserve)",
        what: "How much the U.S. semiconductor industry is producing, from the Federal Reserve's factory output survey.",
        why: "Chip output rises when the whole industry is busy filling orders. It's a broad read on the chip cycle AMD rides.",
        up: "U.S. chip output is higher than a year ago", down: "U.S. chip output is below a year ago" }),
      wiki("Ryzen", "Ryzen", { id: "ryzen-curiosity", name: "Ryzen curiosity", polarity: 1,
        why: "Ryzen is AMD's processor brand for PCs and laptops. Curiosity spikes around launches and PC upgrade waves, a hint of buyer interest before sales numbers come out.",
        up: "more people are looking up Ryzen chips", down: "interest in Ryzen chips is cooling off" }),
      inventory("AMD", { id: "amd-inventory", name: "AMD's stockroom",
        why: "Chipmakers stock up before big launches, but inventory that outruns sales has come before past chip gluts and price cuts. Read it alongside demand signals.",
        up: "AMD is holding more inventory than a year ago (stocking up, or chips waiting for buyers)", down: "AMD is holding less inventory than a year ago" }),
      fred("VIXCLS", { id: "vix-stress", name: "Market stress (VIX)", unit: "index", compare: "recent", threshold: 8, polarity: -1,
        metric: "CBOE Volatility Index (VIX), daily, recent average vs the weeks before",
        what: "We pull the VIX, a free public score of how nervous the stock market feels. Higher = more fear.",
        why: "AMD is a high-flying growth stock. When fear rises, those names often get hit first. This is a risk-mood clue, not a read on chip demand.",
        up: "market stress is elevated versus recent weeks", down: "market stress has eased versus recent weeks" }),
    ],
  },
  {
    ticker: "BA", name: "Boeing", sector: "Aerospace", hnMust: "Boeing",
    news: '"Boeing"',
    signals: [
      fred("ANAPNO", { id: "aircraft-orders", name: "New aircraft orders", unit: "usdM", compare: "recent", threshold: 10, polarity: 1,
        metric: "U.S. manufacturers' new orders for nondefense aircraft and parts (monthly, Census)",
        what: "The dollar value of new civilian aircraft and parts orders U.S. factories booked each month, from the Census Bureau. Boeing is by far the biggest U.S. maker, so this mostly reflects Boeing.",
        why: "Orders are tomorrow's deliveries and revenue. They are lumpy (one airline can order 100 jets in a month), so we compare three months against the three before and only big moves count.",
        up: "aircraft orders picked up versus the prior three months", down: "aircraft orders slowed versus the prior three months" }),
      fred("LOADFACTOR", { id: "load-factor", name: "How full planes are", unit: "pct", compare: "yoy", threshold: 1.5, polarity: 1,
        metric: "Share of airline seats filled on U.S. carriers' scheduled flights (load factor, monthly, BTS)",
        what: "The percentage of seats that are filled on U.S. airlines' flights, published by the Bureau of Transportation Statistics.",
        why: "When planes are packed, airlines need more planes, which means more orders for Boeing. Emptier planes mean airlines can wait.",
        up: "planes are fuller than a year ago, which tends to drive new orders", down: "planes are emptier than a year ago" }),
      tsa({ id: "tsa-ba", name: "Airport security lines", polarity: 1,
        why: "Boeing's customers are airlines. More travelers means busier airlines that need more jets and spare parts.",
        up: "more people are flying than this time last year", down: "fewer people are flying than this time last year" }),
      inventory("Boeing", { id: "boeing-inventory", name: "Boeing's parked-jet pile", params: { concept: "InventoryNetOfAllowancesCustomerAdvancesAndProgressBillings" },
        metric: "Boeing's reported inventory (net of customer advances), from quarterly SEC filings",
        what: "The value of jets and parts Boeing has built or is building but hasn't delivered yet, as reported in its 10-Q and 10-K filings.",
        why: "When delivery problems hit (like the 737 MAX and 787 pauses), finished jets pile up in inventory and cash gets stuck. A shrinking pile usually means deliveries are flowing.",
        up: "Boeing is holding more undelivered inventory than a year ago", down: "Boeing is holding less inventory than a year ago, a sign deliveries are flowing" }),
    ],
  },
  {
    ticker: "JPM", name: "JPMorgan Chase", sector: "Banks", hn: "JPMorgan", hnMust: "JPMorgan|JP Morgan|Dimon|\\bChase\\b",
    news: '("JPMorgan" OR "JP Morgan" OR Dimon)',
    signals: [
      fred("TOTCI", { id: "business-loans", name: "Business loan demand", unit: "usdBnT", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Commercial & industrial loans outstanding at all U.S. banks (weekly, Federal Reserve)",
        what: "How much money U.S. banks have lent to businesses, updated weekly by the Federal Reserve.",
        why: "Banks earn interest on loans. When companies borrow more, the biggest lenders, JPMorgan first among them, have more income-earning loans on the books.",
        up: "businesses are borrowing more than a year ago", down: "business borrowing is below a year ago" }),
      fred("DRCCLACBS", { id: "card-delinquencies", name: "Credit card late payments", unit: "pct", compare: "yoy", threshold: 5, polarity: -1,
        metric: "Delinquency rate on credit card loans at U.S. commercial banks (quarterly, Federal Reserve)",
        what: "The share of credit card balances that are 30+ days past due, published quarterly by the Federal Reserve.",
        why: "Chase is one of America's biggest card issuers. Rising late payments usually come before bigger loan losses and money set aside for them.",
        up: "more card balances are going late than a year ago", down: "fewer card balances are going late than a year ago" }),
      fred("ICSA", { id: "jobless-claims", name: "New jobless claims", unit: "claims", compare: "recent", threshold: 5, polarity: -1,
        metric: "Initial unemployment claims filed per week (Dept. of Labor)",
        what: "How many people file for unemployment benefits for the first time each week, the most up-to-date public read on layoffs.",
        why: "People who lose jobs fall behind on loans. Rising layoffs are an early warning for a bank's credit losses.",
        up: "layoffs are ticking up, a risk for loan repayments", down: "layoffs are easing, which helps borrowers keep paying" }),
      fred("BAMLH0A0HYM2", { id: "hy-spread", name: "Junk-bond stress", unit: "pct", compare: "recent", threshold: 5, polarity: -1,
        metric: "ICE BofA U.S. high-yield option-adjusted spread (daily → compared recent)",
        what: "We pull the junk-bond spread: how much extra interest lenders demand from riskier companies. Wider = credit markets are nervous.",
        why: "When credit markets get nervous, banks face more defaults and fewer deals for their investment bank. Calm credit markets are friendlier for big banks.",
        up: "credit stress is rising (junk spreads are wider)", down: "credit stress is easing (junk spreads are tighter)" }),
    ],
  },
  {
    ticker: "KO", name: "Coca-Cola", sector: "Beverages", hnMust: "Coca-Cola|\\bCoke\\b",
    news: '"Coca-Cola"',
    signals: [
      fred("PSUGAISAUSDM", { id: "sugar", name: "Sugar prices", unit: "centsLb", compare: "yoy", threshold: 5, polarity: -1,
        metric: "Global price of raw sugar, No. 11 contract (monthly, IMF via FRED)",
        what: "The world price of raw sugar, tracked monthly by the International Monetary Fund.",
        why: "Sweeteners are one of Coke's main ingredients worldwide. Pricier sugar raises the cost of every can unless Coke passes it on.",
        up: "sugar is pricier than a year ago, a cost headwind", down: "sugar is cheaper than a year ago, a cost tailwind" }),
      fred("PALUMUSDM", { id: "aluminum", name: "Aluminum (can) prices", unit: "usdTon", compare: "yoy", threshold: 5, polarity: -1,
        metric: "Global price of aluminum (monthly, IMF via FRED)",
        what: "The world price of aluminum, the metal in soda cans, tracked monthly by the International Monetary Fund.",
        why: "Coke sells billions of cans. When aluminum gets pricier, packaging costs rise, and Coke has said tariffs and metal costs push it to change packaging or prices.",
        up: "aluminum is pricier than a year ago, a packaging cost headwind", down: "aluminum is cheaper than a year ago, a packaging cost tailwind" }),
      fred("DTWEXBGS", { id: "dollar", name: "Strength of the U.S. dollar", unit: "index", compare: "recent", threshold: 1.5, polarity: -1,
        metric: "Trade-weighted U.S. dollar index, broad (daily, Federal Reserve)",
        what: "How strong the U.S. dollar is against the currencies of America's trading partners, from the Federal Reserve.",
        why: "Coke makes most of its money outside the U.S. A stronger dollar shrinks those foreign sales when they are converted back into dollars.",
        up: "the dollar is strengthening, which shrinks overseas sales in dollar terms", down: "the dollar is weakening, which boosts overseas sales in dollar terms" }),
    ],
  },
  {
    ticker: "PLTR", name: "Palantir", sector: "AI software / defense", hnMust: "Palantir",
    news: '"Palantir"',
    signals: [
      lever("palantir", "Palantir", { id: "palantir-hiring", name: "Palantir hiring", polarity: 1,
        why: "Palantir's growth depends on engineers it sends to customer sites. A growing jobs board suggests management expects more contracts; a shrinking one suggests caution.",
        up: "Palantir is advertising more roles than at our earlier snapshots", down: "Palantir is advertising fewer roles than at our earlier snapshots" }),
      hn("palantir", { id: "dev-chatter", name: "Tech chatter about Palantir", polarity: 1,
        why: "Palantir sells software to governments and big companies, so engineers' attention is a rough read on how central it is to the AI conversation. Note: chatter includes criticism too.",
        up: "the tech crowd is talking about Palantir more than usual", down: "tech chatter about Palantir has quieted" }),
      wiki("Palantir_Technologies", "Palantir Technologies", { id: "palantir-curiosity", name: "Palantir curiosity", polarity: 1,
        why: "Palantir is one of the most popular stocks with everyday investors. Public curiosity is a gauge of that crowd's attention, which has moved this stock a lot.",
        up: "more people are looking up Palantir than in recent weeks", down: "public curiosity about Palantir is fading" }),
      fred("VIXCLS", { id: "vix-stress", name: "Market stress (VIX)", unit: "index", compare: "recent", threshold: 8, polarity: -1,
        metric: "CBOE Volatility Index (VIX), daily, recent average vs the weeks before",
        what: "We pull the VIX, a free public score of how nervous the stock market feels. Higher = more fear.",
        why: "Palantir trades at a very high valuation, and stocks like that tend to fall hardest when fear rises. This is a risk-mood clue, not a read on Palantir's business.",
        up: "market stress is elevated versus recent weeks", down: "market stress has eased versus recent weeks" }),
    ],
  },
  {
    ticker: "RBLX", name: "Roblox", sector: "Gaming", hnMust: "Roblox",
    news: '"Roblox"',
    signals: [
      wiki("Roblox", "Roblox", { id: "roblox-curiosity", name: "Roblox curiosity", polarity: 1,
        why: "Roblox lives on young players' attention. Spikes in curiosity tend to come with viral games and school breaks; a fade can hint at fewer new players.",
        up: "more people are looking up Roblox than in recent weeks", down: "interest in Roblox is cooling off" }),
      greenhouse("roblox", "Roblox", { id: "roblox-hiring", name: "Roblox hiring", polarity: 1,
        why: "Hiring is a forward-looking budget decision. A growing jobs board suggests management expects growth; cuts suggest it's tightening up.",
        up: "Roblox is advertising more roles than at our earlier snapshots", down: "Roblox is advertising fewer roles than at our earlier snapshots" }),
    ],
  },
  {
    ticker: "SHOP", name: "Shopify", sector: "E-commerce software", hnMust: "Shopify",
    news: '"Shopify"',
    signals: [
      npm("@shopify/shopify-api", { id: "shopify-sdk", name: "Developers building Shopify apps", polarity: 1,
        what: "Daily downloads of @shopify/shopify-api, Shopify's official JavaScript toolkit for building store apps. Apps and integrations that plug into Shopify install it.",
        why: "Shopify grows when more merchants and app makers build on it. More installs means more apps being built and deployed, a grassroots read on the ecosystem.",
        up: "more developers are building on Shopify than a month ago", down: "Shopify toolkit installs have dipped versus the prior month" }),
      fred("RSNSR", { id: "online-sales", name: "Online store sales", unit: "usdM", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Monthly U.S. sales at nonstore retailers (mostly online), Census",
        what: "Monthly sales at 'nonstore retailers', the Census category that is mostly online shopping.",
        why: "Shopify takes a small cut of the sales its merchants make. When online shopping grows overall, Shopify's merchants usually sell more too.",
        up: "online sales are growing versus last year", down: "online sales are running below last year" }),
      hn("shopify", { id: "dev-chatter", name: "Developer chatter about Shopify", polarity: 1,
        why: "Developers talk about the platforms they build on. A rise in chatter often follows big product launches; a slump can mean attention has moved elsewhere.",
        up: "developers are talking about Shopify more than usual", down: "developer chatter about Shopify has quieted" }),
    ],
  },
  {
    ticker: "UAL", name: "United Airlines", sector: "Airlines", hn: "United Airlines", hnMust: "United Airlines|\\bUnited\\b.*\\b(flight|airline|plane|jet)",
    news: '"United Airlines"',
    signals: [
      tsa({ id: "tsa-ual", name: "Airport security lines", polarity: 1,
        why: "More people in TSA lines means fuller planes. TSA posts numbers every day, so this is a near real-time read on air-travel demand.",
        up: "more people are flying than this time last year", down: "fewer people are flying than this time last year" }),
      fred("DJFUELUSGULF", { id: "jet-fuel", name: "Jet fuel price", unit: "usdGal", compare: "recent", threshold: 3, polarity: -1,
        metric: "U.S. Gulf Coast kerosene-type jet fuel spot price (daily)",
        what: "The wholesale price of jet fuel on the U.S. Gulf Coast, published by the EIA via FRED.",
        why: "Fuel is one of an airline's biggest costs. United doesn't hedge much, so jet fuel moves hit its profit fairly directly.",
        up: "jet fuel is getting more expensive, a cost headwind", down: "jet fuel is getting cheaper, a cost tailwind" }),
      fred("LOADFACTOR", { id: "load-factor", name: "How full planes are", unit: "pct", compare: "yoy", threshold: 1.5, polarity: 1,
        metric: "Share of airline seats filled on U.S. carriers' scheduled flights (load factor, monthly, BTS)",
        what: "The percentage of seats that are filled on U.S. airlines' flights, published by the Bureau of Transportation Statistics.",
        why: "Fuller planes mean airlines can charge more and spread fixed costs over more passengers.",
        up: "planes are fuller than a year ago", down: "planes are emptier than a year ago" }),
      fred("CUSR0000SETG01", { id: "airfares", name: "Airfares", unit: "index", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Consumer price index for airline fares (monthly, BLS)",
        what: "How much ticket prices have changed for U.S. travelers, from the government's consumer price index.",
        why: "Higher fares with planes still full means strong demand and more revenue per seat. Falling fares usually mean airlines are cutting prices to fill seats.",
        up: "airfares are higher than a year ago, a sign of pricing power", down: "airfares are lower than a year ago, a sign of discounting" }),
    ],
  },
];

// Illustrative ideas + research notes. Live proxies (when we found free, frequent public data) are wired into curated stocks above.
export const IDEAS = [
  { title: "Recycling volumes → electronics demand", body: "City e-waste tonnage is usually yearly (EPA ADEPT / Facts & Figures). Live proxy now on Amazon: U.S. paperboard mill production (FRED IPN32213N) plus cardboard box prices — packaging volume and price as a stand-in for goods moving through the system. True municipal recycling feeds stay 'ideas' until a free weekly national series appears.", status: "partial", liveOn: "AMZN" },
  { title: "Moth & pest counts → unsold inventory", body: "The warehouse-moth anecdote never had a free national feed. FWS refuge moth inventories (data.gov) are one-off surveys, not a market series. Still an idea — we won't invent numbers.", status: "idea" },
  { title: "Satellite parking-lot counts → store traffic", body: "Commercial vendors (Orbital Insight-style) charge for car counts. Free Sentinel/Landsat revisit is too slow and cloudy for weekly retail traffic, and scraping Google Popular Times violates terms. Still an idea; no honest free substitute yet.", status: "idea" },
  { title: "Fuel storage from satellites → oil inventories", body: "Live now on ExxonMobil: weekly U.S. commercial crude stocks excl. SPR from the EIA (series WCESTUS1) — the official inventory print markets already watch. Satellite tank-farm estimates remain paid; the EIA series is the free, legal version of the same idea.", status: "live", liveOn: "XOM" },
];
