// The curated universe: well-known tickers, each mapped to offbeat public signals.
// polarity: +1 = a rise has historically been a tailwind for the company, -1 = a rise is a headwind,
// 0 = context only (direction is ambiguous for this company). These are hedged, educational framings.

const SRC = {
  fred: "FRED, Federal Reserve Bank of St. Louis",
  wiki: "Wikimedia pageviews API",
  pypi: "PyPI download stats (pypistats.org)",
  hn: "Hacker News (Algolia search API)",
  openfda: "openFDA (U.S. Food & Drug Administration)",
  nhtsa: "NHTSA complaints API",
  tsa: "TSA checkpoint travel numbers",
  greenhouse: "Company job board (Greenhouse public API)",
  sec: "SEC EDGAR XBRL data",
  eia: "U.S. Energy Information Administration (EIA)",
};

// ---- reusable signal builders ----
const fred = (series, o) => ({ source: "fred", params: { series }, sourceName: SRC.fred, ...o });
const wiki = (article, label, o) => ({
  source: "wiki", params: { article }, sourceName: SRC.wiki, unit: "views", compare: "recent", threshold: 8,
  metric: `Daily views of the English Wikipedia article “${label}”`,
  what: `How many people look up “${label}” on Wikipedia each day. It is a free, public stand-in for search interest: when curiosity spikes, pageviews usually spike too.`,
  ...o,
});
const pypi = (pkg, o) => ({
  source: "pypi", params: { pkg }, sourceName: SRC.pypi, unit: "downloads", compare: "recent", threshold: 5,
  metric: `Daily downloads of the “${pkg}” Python package`,
  ...o,
});
const hn = (query, o) => ({
  source: "hn", params: { query }, sourceName: SRC.hn, unit: "stories", compare: "recent", threshold: 15,
  metric: `Hacker News stories per week mentioning “${query}”`,
  what: `How often “${query}” shows up in stories posted to Hacker News, the news board many software engineers read. It is a rough gauge of developer chatter.`,
  ...o,
});
const tsa = (o) => ({
  source: "tsa", params: {}, sourceName: SRC.tsa, unit: "travelers", compare: "yoy7", threshold: 2,
  metric: "People screened at TSA airport checkpoints per day (7-day average vs the same week last year)",
  what: "The number of travelers passing through U.S. airport security every day, published by the TSA. It is one of the fastest public reads on how much Americans are traveling.",
  ...o,
});
const greenhouse = (board, name, o) => ({
  source: "greenhouse", params: { board }, sourceName: SRC.greenhouse, unit: "roles", compare: "snapshot", threshold: 5,
  metric: `Open roles listed on ${name}'s public job board`,
  what: `A count of the jobs ${name} is advertising right now on its public careers board. Companies tend to hire ahead of growth and freeze hiring ahead of slowdowns.`,
  ...o,
});
const inventory = (name, o) => ({
  source: "secInventory", params: {}, sourceName: SRC.sec, unit: "usdB", compare: "yoy", threshold: 10, polarity: -1,
  metric: `${name}'s reported inventory, from quarterly SEC filings`,
  what: `The dollar value of products ${name} has built or bought but not yet sold, as reported in its 10-Q and 10-K filings. It is the corporate version of a stockroom count.`,
  ...o,
});
const gas = (o) => fred("GASREGW", { unit: "usdGal", compare: "recent", threshold: 2, metric: "U.S. average regular gasoline price (weekly)", what: "The average price drivers pay for a gallon of regular gas across the U.S., surveyed weekly by the Energy Information Administration and published on FRED.", ...o });

export const TICKERS = [
  {
    ticker: "AAPL", name: "Apple", sector: "Consumer tech",
    news: '"Apple" (iPhone OR Mac OR iPad OR "Tim Cook")',
    signals: [
      wiki("IPhone", "iPhone", { id: "iphone-curiosity", name: "iPhone curiosity", polarity: 1,
        why: "iPhones are roughly half of Apple's revenue. Rising public curiosity about the iPhone often shows up around launches and upgrade waves, and a fade can hint at a quieter cycle.",
        up: "more people are curious about iPhones, which tends to come with upgrade interest", down: "interest in iPhones is cooling off compared with recent weeks" }),
      fred("MRTSSM443USS", { id: "electronics-stores", name: "Electronics store sales", unit: "usdM", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Monthly U.S. sales at electronics & appliance stores (Census, seasonally adjusted)",
        what: "How much Americans spend each month at electronics and appliance stores, from the Census Bureau's retail survey.",
        why: "Apple sells a lot of hardware through retailers. Store sales for gadgets are a broad read on whether shoppers are opening their wallets for electronics at all.",
        up: "shoppers are spending more on electronics than a year ago", down: "electronics spending is running below last year" }),
      inventory("Apple", { id: "apple-inventory", name: "Apple's stockroom",
        why: "Apple runs famously lean inventory. A jump in inventory can mean products are not selling as fast as planned, or that Apple is stocking up ahead of a launch, so it is a signal to watch rather than a verdict.",
        up: "Apple is holding more unsold product than a year ago", down: "Apple is holding less product than a year ago, consistent with lean, fast-selling inventory" }),
    ],
  },
  {
    ticker: "NVDA", name: "Nvidia", sector: "Semiconductors / AI",
    news: '"Nvidia"',
    signals: [
      pypi("torch", { id: "pytorch-installs", name: "AI builders installing PyTorch", polarity: 1,
        what: "How many times PyTorch, the most popular toolkit for building AI models, is downloaded each day. Most serious PyTorch work runs on Nvidia GPUs.",
        why: "Every developer installing PyTorch is someone building or running AI models, and most of that runs on Nvidia hardware. It is a grassroots read on AI activity, well upstream of data-center orders.",
        up: "more developers are pulling down AI tooling than a month ago", down: "AI tooling downloads have slowed versus the prior month" }),
      hn("nvidia", { id: "dev-chatter", name: "Developer chatter about Nvidia", polarity: 1,
        why: "Engineers talk about the chips they want and can't get. A rise in chatter often tracks product launches and demand; a slump can mean attention has moved elsewhere.",
        up: "engineers are talking about Nvidia more than usual", down: "developer chatter about Nvidia has quieted" }),
      inventory("Nvidia", { id: "nvidia-inventory", name: "Nvidia's stockroom",
        why: "Chipmakers build inventory before big product ramps, but a pile-up that outruns sales has preceded past chip gluts. Read it alongside demand signals.",
        up: "Nvidia is holding more inventory than a year ago (stocking up for demand, or chips waiting for buyers)", down: "Nvidia is holding less inventory than a year ago" }),
      fred("VIXCLS", { id: "vix-stress", name: "Market stress (VIX)", unit: "index", compare: "recent", threshold: 8, polarity: -1,
        metric: "CBOE Volatility Index (VIX), weekly average vs the weeks before",
        what: "The VIX is a market-implied gauge of expected stock-market turbulence. When it jumps, investors are paying up for protection.",
        why: "Scout find: weekly VIX moves have lined up inversely with high-beta tech (including Nvidia) in our recent sample. Rising stress has historically been a headwind for richly valued growth names. Correlation ≠ causation — treat as context for risk appetite, not a chip-demand read.",
        up: "market stress is elevated versus recent weeks", down: "market stress has eased versus recent weeks" }),
    ],
  },
  {
    ticker: "MSFT", name: "Microsoft", sector: "Software / cloud",
    news: '"Microsoft" (Azure OR Copilot OR Windows OR Nadella)',
    signals: [
      pypi("azure-core", { id: "azure-sdk", name: "Developers wiring up Azure", polarity: 1,
        what: "Daily downloads of azure-core, the shared foundation of Microsoft's Azure Python SDKs. Software that talks to Azure installs it.",
        why: "Cloud is Microsoft's growth engine. More installs of the Azure SDK means more code being built and deployed against Azure, a ground-level hint of cloud usage.",
        up: "more code is being built against Azure than a month ago", down: "Azure SDK installs have dipped versus the prior month" }),
      wiki("Microsoft_Copilot", "Microsoft Copilot", { id: "copilot-curiosity", name: "Copilot curiosity", polarity: 1,
        why: "Copilot is Microsoft's big AI bet for Office and Windows. Public curiosity is an early read on whether the AI pitch is reaching regular users.",
        up: "public curiosity about Copilot is rising", down: "curiosity about Copilot is fading versus recent weeks" }),
      hn("copilot", { id: "copilot-chatter", name: "Developer chatter about Copilot", polarity: 1,
        why: "GitHub Copilot, owned by Microsoft, is one of the most-used AI coding tools. Engineers discussing it is a sign it stays relevant in a crowded field.",
        up: "developers are discussing Copilot more than usual", down: "developer chatter about Copilot has slowed" }),
    ],
  },
  {
    ticker: "TSLA", name: "Tesla", sector: "Autos / EVs",
    news: '"Tesla" (Musk OR electric OR "Model Y" OR Cybertruck)',
    signals: [
      { id: "modely-complaints", name: "Model Y owner complaints", source: "nhtsa", params: { make: "TESLA", model: "MODEL Y (ALL VARIANTS)", years: [2023, 2024, 2025, 2026] }, sourceName: SRC.nhtsa,
        unit: "complaints", compare: "recent", threshold: 15, polarity: -1,
        metric: "Owner complaints filed with NHTSA about 2023–2026 Model Ys, per month",
        what: "Complaints Model Y owners file with the National Highway Traffic Safety Administration, the federal auto-safety regulator. A surge is how many recalls and investigations start.",
        why: "The Model Y is Tesla's best-selling car. A rising complaint count can foreshadow recalls, investigations, and warranty costs. (More cars on the road also means more complaints, so sharp jumps matter more than slow drift.)",
        up: "complaints are climbing faster than the prior few months", down: "complaints have eased compared with the prior few months" },
      wiki("Tesla_Model_Y", "Tesla Model Y", { id: "modely-curiosity", name: "Model Y curiosity", polarity: 1,
        why: "Curiosity about Tesla's best-seller is a free proxy for shopping interest, ahead of the quarterly delivery numbers.",
        up: "more people are looking up the Model Y", down: "interest in the Model Y is cooling off" }),
      gas({ id: "gas-ev", name: "Pain at the pump", polarity: 1,
        why: "Expensive gas makes electric cars look like a better deal. High or rising gas prices have historically nudged more shoppers toward EVs.",
        up: "gas is getting pricier, which makes EVs look more attractive", down: "gas is getting cheaper, which weakens the money-saving pitch for EVs" }),
    ],
  },
  {
    ticker: "AMZN", name: "Amazon", sector: "E-commerce / cloud",
    news: '"Amazon" (AWS OR Prime OR Jassy OR retail)',
    signals: [
      fred("PCU322211322211", { id: "cardboard", name: "Cardboard box prices", unit: "index", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Producer price index for corrugated & solid fiber boxes (monthly)",
        what: "What box makers charge for corrugated cardboard boxes, tracked by the Bureau of Labor Statistics. When demand for boxes is strong, box makers can raise prices.",
        why: "Almost every Amazon order ships in a box. Firm box prices hint at healthy shipping volume across e-commerce; slumping prices can mean fewer packages moving.",
        up: "box prices are up from a year ago, a hint of firm demand for shipping boxes", down: "box prices are below last year, a hint of softer package volume" }),
      fred("IPN32213N", { id: "paperboard", name: "U.S. paperboard production", unit: "index", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Industrial production index for paperboard mills (monthly, Federal Reserve)",
        what: "How much paperboard U.S. mills are producing — the raw material behind corrugated boxes and much of the cardboard packaging stream. A free public stand-in for the 'recycling / packaging volumes → goods demand' idea (city e-waste tonnage is only published yearly).",
        why: "More paperboard usually means more boxes being made for goods moving through warehouses and e-commerce. Soft production can mean fewer packages in the system.",
        up: "mills are producing more paperboard than a year ago", down: "paperboard production is below a year ago" }),
      fred("RSNSR", { id: "online-sales", name: "Online store sales", unit: "usdM", compare: "yoy", threshold: 3, polarity: 1,
        metric: "Monthly U.S. sales at nonstore retailers (mostly online), Census",
        what: "Monthly sales at 'nonstore retailers', the Census category that is mostly online shopping.",
        why: "Amazon is the biggest player in U.S. online retail, so the whole category growing is a rising tide for it.",
        up: "online sales are growing versus last year", down: "online sales are running below last year" }),
      pypi("boto3", { id: "aws-sdk", name: "Developers wiring up AWS", polarity: 1,
        what: "Daily downloads of boto3, the official Python toolkit for Amazon Web Services. Almost any Python code that touches AWS installs it.",
        why: "AWS earns most of Amazon's profit. More boto3 installs means more software being built and deployed on AWS.",
        up: "more code is being deployed against AWS than a month ago", down: "AWS toolkit installs have dipped versus the prior month" }),
    ],
  },
  {
    ticker: "WMT", name: "Walmart", sector: "Retail",
    news: '"Walmart"',
    signals: [
      fred("APU0000708111", { id: "egg-prices", name: "Egg prices", unit: "usdDozen", compare: "yoy", threshold: 5, polarity: 1,
        metric: "Average U.S. price of a dozen large Grade A eggs (BLS, monthly)",
        what: "What a dozen eggs costs at the store on average, from the Bureau of Labor Statistics. Eggs are a famously visible grocery price.",
        why: "When grocery bills jump, shoppers have historically traded down to discount grocers, and Walmart is the biggest one. Pricier eggs can mean more trips to Walmart, though it also squeezes margins.",
        up: "grocery staples are pricier than a year ago, which tends to push shoppers toward discounters", down: "grocery staples are cheaper than a year ago, easing the pressure to trade down" }),
      gas({ id: "gas-wallet", name: "Gas squeeze on shoppers", polarity: -1,
        why: "Walmart's core shoppers drive to the store and feel gas prices directly. Every extra dollar at the pump is a dollar not spent in the aisles.",
        up: "gas is getting pricier, leaving shoppers less to spend", down: "gas is getting cheaper, leaving shoppers a little more to spend" }),
      fred("ICSA", { id: "jobless-claims", name: "New jobless claims", unit: "claims", compare: "recent", threshold: 5, polarity: 0,
        metric: "Initial unemployment claims filed per week (Dept. of Labor)",
        what: "How many people file for unemployment benefits for the first time each week, the most up-to-date public read on layoffs.",
        why: "Rising layoffs squeeze spending, but Walmart has historically held up better than most retailers in downturns because shoppers trade down. That is why we treat this one as context rather than good or bad.",
        up: "layoffs are ticking up", down: "layoffs are easing" }),
    ],
  },
  {
    ticker: "DAL", name: "Delta Air Lines", sector: "Airlines", hn: "Delta airline", hnMust: "\\bDelta\\b",
    news: '"Delta Air Lines"',
    signals: [
      tsa({ id: "tsa-dal", name: "Airport security lines", polarity: 1,
        why: "More people in TSA lines means fuller planes. Airlines report quarterly, but TSA posts numbers every day, so this is a near real-time read on air-travel demand.",
        up: "more people are flying than this time last year", down: "fewer people are flying than this time last year" }),
      fred("DJFUELUSGULF", { id: "jet-fuel", name: "Jet fuel price", unit: "usdGal", compare: "recent", threshold: 3, polarity: -1,
        metric: "U.S. Gulf Coast kerosene-type jet fuel spot price (daily)",
        what: "The wholesale price of jet fuel on the U.S. Gulf Coast, published by the EIA via FRED.",
        why: "Fuel is one of an airline's biggest costs, often a quarter of expenses. Rising jet fuel eats directly into profit unless fares rise too.",
        up: "jet fuel is getting more expensive, a cost headwind", down: "jet fuel is getting cheaper, a cost tailwind" }),
    ],
  },
  {
    ticker: "UNP", name: "Union Pacific", sector: "Railroads",
    news: '"Union Pacific"',
    signals: [
      fred("RAILFRTCARLOADSD11", { id: "rail-carloads", name: "Rail carloads", unit: "carloads", compare: "yoy", threshold: 2, polarity: 1,
        metric: "U.S. rail freight carloads per month (seasonally adjusted, BTS)",
        what: "How many freight carloads U.S. railroads move each month, from the Bureau of Transportation Statistics.",
        why: "Railroads get paid by the load. Carloads are close to a direct read on Union Pacific's business volume, published well before earnings.",
        up: "railroads are hauling more than a year ago", down: "railroads are hauling less than a year ago" }),
      fred("TRUCKD11", { id: "truck-tonnage", name: "Truck tonnage", unit: "index", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Truck tonnage index (monthly, seasonally adjusted, BTS)",
        what: "An index of how much freight trucks haul, from the Bureau of Transportation Statistics. It is a broad gauge of goods moving through the economy.",
        why: "Trucks and trains move the same economy. When trucking volume rises, there is usually more freight for railroads too.",
        up: "the freight economy is busier than a year ago", down: "the freight economy is slower than a year ago" }),
      fred("PERMIT", { id: "building-permits", name: "Building permits", unit: "thousandUnits", compare: "yoy", threshold: 3, polarity: 1,
        metric: "U.S. building permits for new private housing (monthly, Census)",
        what: "How many new privately owned housing units are authorized by building permits — a forward-looking housing start signal.",
        why: "Scout find: permit growth has moved with Union Pacific in our recent sample. Housing activity pulls lumber, appliances, and materials that often ride the rails. A soft permits print can mean less construction-related freight ahead.",
        up: "builders are permitting more homes than a year ago", down: "builders are permitting fewer homes than a year ago" }),
    ],
  },
  {
    ticker: "LLY", name: "Eli Lilly", hnMust: "Lilly|Zepbound|Mounjaro|tirzepatide", sector: "Pharma",
    news: '("Eli Lilly" OR Zepbound OR Mounjaro)',
    signals: [
      { id: "tirzepatide-reports", name: "Mounjaro/Zepbound usage footprint", source: "openfda", params: { generic: "tirzepatide" }, sourceName: SRC.openfda,
        unit: "reports", compare: "yoy", threshold: 10, polarity: 1,
        metric: "Monthly FDA adverse-event reports that mention tirzepatide (Mounjaro, Zepbound)",
        what: "Reports of side effects filed with the FDA that mention tirzepatide, Lilly's blockbuster weight-loss and diabetes drug. Report counts tend to grow with the number of people taking a drug.",
        why: "More patients means more reports, so the trend is a rough, unusual proxy for how fast use is growing. Caveat: a spike can also mean a real safety concern, so this is a signal to read carefully.",
        up: "the drug's footprint is growing versus a year ago", down: "report volume is below a year ago" },
      wiki("Tirzepatide", "Tirzepatide", { id: "tirzepatide-curiosity", name: "Tirzepatide curiosity", polarity: 1,
        why: "Public curiosity about Lilly's weight-loss drug is an early read on patient demand, before prescription data shows up in earnings.",
        up: "curiosity about tirzepatide is rising", down: "curiosity about tirzepatide is cooling off" }),
    ],
  },
  {
    ticker: "NVO", name: "Novo Nordisk", hn: "Ozempic", hnMust: "Novo|Ozempic|Wegovy|semaglutide", sector: "Pharma",
    news: '("Novo Nordisk" OR Wegovy OR Ozempic)',
    signals: [
      { id: "semaglutide-reports", name: "Ozempic/Wegovy usage footprint", source: "openfda", params: { generic: "semaglutide" }, sourceName: SRC.openfda,
        unit: "reports", compare: "yoy", threshold: 10, polarity: 1,
        metric: "Monthly FDA adverse-event reports that mention semaglutide (Ozempic, Wegovy)",
        what: "Reports of side effects filed with the FDA that mention semaglutide, Novo's blockbuster drug. Report counts tend to grow with the number of people taking a drug.",
        why: "More patients means more reports, so the trend is a rough proxy for how fast use is growing in the U.S. Caveat: a spike can also flag a real safety issue.",
        up: "the drug's footprint is growing versus a year ago", down: "report volume is below a year ago" },
      wiki("Semaglutide", "Semaglutide", { id: "semaglutide-curiosity", name: "Semaglutide curiosity", polarity: 1,
        why: "Public curiosity about Ozempic's active ingredient is an early read on patient demand.",
        up: "curiosity about semaglutide is rising", down: "curiosity about semaglutide is cooling off" }),
      wiki("Tirzepatide", "Tirzepatide", { id: "rival-curiosity", name: "Rival drug buzz", polarity: -1,
        why: "Tirzepatide is Eli Lilly's competing drug. When curiosity about the rival rises, it can signal patients and doctors shifting attention away from Novo.",
        up: "the rival drug is drawing more attention", down: "attention on the rival drug is cooling" }),
    ],
  },
  {
    ticker: "HD", name: "Home Depot", sector: "Home improvement",
    news: '"Home Depot"',
    signals: [
      fred("HOUST", { id: "housing-starts", name: "New homes breaking ground", unit: "thousandUnits", compare: "yoy", threshold: 3, polarity: 1,
        metric: "New privately-owned housing units started (annualized, monthly, Census)",
        what: "How many new homes builders started constructing, from the Census Bureau. Every new home needs lumber, fixtures, and appliances.",
        why: "Builders and pros are a big slice of Home Depot's sales, and new homeowners spend heavily on improvements. More starts means more demand down the line.",
        up: "builders are breaking ground on more homes than a year ago", down: "builders are starting fewer homes than a year ago" }),
      fred("MORTGAGE30US", { id: "mortgage-rates", name: "Mortgage rates", unit: "pct", compare: "recent", threshold: 2, polarity: -1,
        metric: "Average 30-year fixed mortgage rate (Freddie Mac, weekly)",
        what: "The average rate on a 30-year fixed mortgage, surveyed weekly by Freddie Mac.",
        why: "People renovate when they buy, sell, or refinance. High mortgage rates freeze the housing market, and with it a lot of big-ticket home projects.",
        up: "mortgages are getting pricier, which tends to freeze home projects", down: "mortgage rates are easing, which can thaw housing activity" }),
      fred("WPU081", { id: "lumber", name: "Lumber prices", unit: "index", compare: "yoy", threshold: 3, polarity: 0,
        metric: "Producer price index for lumber (monthly, BLS)",
        what: "What lumber mills charge for wood, tracked by the Bureau of Labor Statistics.",
        why: "Pricier lumber raises the dollar value of each sale, but it can also price out DIY projects. That is why we treat it as context rather than good or bad.",
        up: "lumber is pricier than a year ago", down: "lumber is cheaper than a year ago" }),
    ],
  },
  {
    ticker: "MCD", name: "McDonald's", hnMust: "McDonald", sector: "Restaurants",
    news: '"McDonald\'s"',
    signals: [
      fred("APU0000703112", { id: "beef", name: "Ground beef prices", unit: "usdLb", compare: "yoy", threshold: 4, polarity: -1,
        metric: "Average U.S. price of 100% ground beef per pound (BLS, monthly)",
        what: "What a pound of ground beef costs at retail, from the Bureau of Labor Statistics.",
        why: "Beef is the core of the menu. Rising beef costs squeeze margins for McDonald's and its franchisees unless they raise prices.",
        up: "beef is pricier than a year ago, a cost headwind", down: "beef is cheaper than a year ago, a cost tailwind" }),
      fred("CUSR0000SEFV", { id: "eating-out", name: "Price of eating out", unit: "index", compare: "yoy", threshold: 3, polarity: 0,
        metric: "Consumer price index for food away from home (monthly, BLS)",
        what: "How fast restaurant prices are rising across the U.S., from the consumer price index.",
        why: "Rising menu prices lift revenue per order, but when eating out gets too expensive, budget diners cut back. That is why we treat it as context.",
        up: "restaurant prices are rising faster", down: "restaurant price growth is slowing" }),
      fred("APU0000708111", { id: "eggs-breakfast", name: "Egg prices (breakfast costs)", unit: "usdDozen", compare: "yoy", threshold: 5, polarity: -1,
        metric: "Average U.S. price of a dozen large Grade A eggs (BLS, monthly)",
        what: "What a dozen eggs costs on average, from the Bureau of Labor Statistics.",
        why: "Breakfast is a big, high-margin daypart, and the Egg McMuffin runs on eggs. Egg spikes have squeezed restaurant costs before.",
        up: "eggs are pricier than a year ago, a breakfast cost headwind", down: "eggs are cheaper than a year ago, easing breakfast costs" }),
    ],
  },
  {
    ticker: "XOM", name: "ExxonMobil", sector: "Energy", hn: "Exxon", hnMust: "\\bExxon",
    news: '("ExxonMobil" OR "Exxon Mobil")',
    signals: [
      fred("DCOILWTICO", { id: "wti", name: "Crude oil price", unit: "usdBbl", compare: "recent", threshold: 3, polarity: 1,
        metric: "WTI crude oil spot price (daily, EIA)",
        what: "The price of a barrel of West Texas Intermediate crude, the U.S. oil benchmark.",
        why: "Exxon pumps millions of barrels a day. Every dollar move in oil flows fairly directly into its profit.",
        up: "oil is getting more expensive, which lifts producer profits", down: "oil is getting cheaper, which trims producer profits" }),
      { id: "crude-stocks", name: "U.S. crude oil in storage", source: "eiaWeeklyXls", params: { series: "WCESTUS1" }, sourceName: SRC.eia,
        unit: "kbbl", compare: "recent", threshold: 1.5, polarity: -1,
        metric: "Weekly U.S. ending stocks of crude oil excluding the Strategic Petroleum Reserve (thousand barrels)",
        what: "How many barrels of commercial crude sit in U.S. tanks, pipelines, and storage — the same inventory idea hedge funds chase with 'fuel storage from satellites,' published weekly for free by the EIA.",
        why: "Building inventories usually mean more supply than the market is absorbing, which has historically weighed on oil prices and producer profits. Drawing inventories is the opposite.",
        up: "commercial crude stocks are building versus the prior weeks", down: "commercial crude stocks are being drawn down versus the prior weeks" },
      gas({ id: "gas-refining", name: "Gas pump prices", polarity: 1,
        why: "Exxon is also one of the biggest refiners. Firm gasoline prices usually go with healthy refining margins.",
        up: "gas prices are firming", down: "gas prices are easing" }),
    ],
  },
  {
    ticker: "COIN", name: "Coinbase", sector: "Crypto / fintech",
    news: '"Coinbase"',
    signals: [
      fred("CBBTCUSD", { id: "bitcoin", name: "Bitcoin price", unit: "usd", compare: "recent", threshold: 5, polarity: 1,
        metric: "Bitcoin price on Coinbase (daily, via FRED)",
        what: "The price of one bitcoin on Coinbase's exchange, as recorded daily by FRED.",
        why: "Coinbase earns most of its money from trading fees, and trading surges when crypto prices run.",
        up: "bitcoin is climbing, which usually brings traders back", down: "bitcoin is sliding, which usually cools trading" }),
      wiki("Bitcoin", "Bitcoin", { id: "bitcoin-curiosity", name: "Bitcoin curiosity", polarity: 1,
        why: "Retail curiosity tends to rise before new people open exchange accounts. It is a crowd-mood gauge for crypto.",
        up: "regular people are getting curious about bitcoin again", down: "public curiosity about bitcoin is fading" }),
      greenhouse("coinbase", "Coinbase", { id: "coinbase-hiring", name: "Coinbase hiring", polarity: 1,
        why: "Crypto companies hire aggressively in boom times and cut hard in busts. The hiring board is a window into how management sees the road ahead.",
        up: "Coinbase is advertising more roles than at our earlier snapshots", down: "Coinbase is advertising fewer roles than at our earlier snapshots" }),
    ],
  },
  {
    ticker: "ABNB", name: "Airbnb", sector: "Travel",
    news: '"Airbnb"',
    signals: [
      tsa({ id: "tsa-abnb", name: "Airport security lines", polarity: 1,
        why: "Many Airbnb stays start with a flight. Daily TSA counts are a near real-time read on travel demand.",
        up: "more people are traveling than this time last year", down: "fewer people are traveling than this time last year" }),
      fred("CUSR0000SEHB", { id: "lodging-prices", name: "Hotel & lodging prices", unit: "index", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Consumer price index for lodging away from home (monthly, BLS)",
        what: "How fast prices for hotels and other short-term lodging are rising, from the consumer price index.",
        why: "When hotels get pricier, travelers look for alternatives and hosts can charge more. Firm lodging prices are usually good for Airbnb's take.",
        up: "lodging prices are rising, a sign of firm travel demand", down: "lodging prices are softening" }),
      greenhouse("airbnb", "Airbnb", { id: "airbnb-hiring", name: "Airbnb hiring", polarity: 1,
        why: "Hiring is a forward-looking budget decision. A growing jobs board suggests management expects growth.",
        up: "Airbnb is advertising more roles than at our earlier snapshots", down: "Airbnb is advertising fewer roles than at our earlier snapshots" }),
      fred("UNRATE", { id: "unemployment", name: "U.S. unemployment rate", unit: "pct", compare: "recent", threshold: 3, polarity: -1,
        metric: "U.S. civilian unemployment rate (monthly, BLS)",
        what: "The share of the labor force that is unemployed and looking for work — the headline jobs-market thermometer.",
        why: "Scout find: unemployment tends to lead Airbnb's stock moves by about a month in our sample (higher joblessness ↔ softer shares). Layoffs squeeze discretionary travel budgets. Read it alongside TSA lines and lodging prices.",
        up: "the unemployment rate is rising versus recent months", down: "the unemployment rate is easing versus recent months" }),
    ],
  },
  {
    ticker: "DIS", name: "Disney", sector: "Media / parks",
    news: '"Disney" (parks OR Iger OR "box office" OR streaming)',
    signals: [
      wiki("Walt_Disney_World", "Walt Disney World", { id: "wdw-curiosity", name: "Disney World trip planning", polarity: 1,
        why: "Parks and experiences are Disney's biggest profit engine. People research a trip before they book, so curiosity about Disney World is an early demand hint.",
        up: "more people are researching Disney World", down: "interest in Disney World is cooling off" }),
      tsa({ id: "tsa-dis", name: "Airport security lines", polarity: 1,
        why: "Many park visitors fly in. Daily TSA counts are a near real-time read on travel demand.",
        up: "more people are flying than this time last year", down: "fewer people are flying than this time last year" }),
      fred("UMCSENT", { id: "sentiment", name: "Consumer mood", unit: "index", compare: "yoy", threshold: 4, polarity: 1,
        metric: "University of Michigan consumer sentiment index (monthly)",
        what: "A monthly survey of how upbeat Americans feel about their finances and the economy.",
        why: "A Disney vacation is a big discretionary purchase. Families book them when they feel good about money.",
        up: "Americans are feeling better about money than a year ago", down: "Americans are gloomier about money than a year ago" }),
    ],
  },
  {
    ticker: "F", name: "Ford", sector: "Autos",
    news: '("Ford Motor" OR "Ford F-150")',
    signals: [
      { id: "f150-complaints", name: "F-150 owner complaints", source: "nhtsa", params: { make: "FORD", model: "F-150 (SUPER CREW) GAS", years: [2023, 2024, 2025, 2026] }, sourceName: SRC.nhtsa,
        unit: "complaints", compare: "recent", threshold: 15, polarity: -1,
        metric: "Owner complaints filed with NHTSA about 2023–2026 F-150 SuperCrew (gas), per month",
        what: "Complaints F-150 owners file with the National Highway Traffic Safety Administration. Complaint surges are how many recalls and investigations start.",
        why: "The F-Series is Ford's profit machine, and Ford has led the industry in recalls. Rising complaints can foreshadow recall and warranty costs.",
        up: "complaints are climbing versus the prior few months", down: "complaints have eased versus the prior few months" },
      fred("TOTALSA", { id: "vehicle-sales", name: "U.S. vehicle sales pace", unit: "millionUnits", compare: "yoy", threshold: 2, polarity: 1,
        metric: "Total U.S. light vehicle sales, annualized (monthly, BEA)",
        what: "How many new cars and light trucks Americans are buying, as an annual pace.",
        why: "A rising tide for the whole industry. Ford's U.S. sales tend to move with the market.",
        up: "Americans are buying cars at a faster pace than a year ago", down: "car buying is slower than a year ago" }),
      gas({ id: "gas-trucks", name: "Gas prices vs. trucks", polarity: -1,
        why: "Ford's lineup leans on big trucks and SUVs. Expensive gas has historically pushed shoppers toward smaller, thriftier vehicles.",
        up: "gas is getting pricier, a headwind for big trucks", down: "gas is getting cheaper, which helps truck demand" }),
      fred("BAMLH0A0HYM2", { id: "hy-spread", name: "Junk-bond stress", unit: "pct", compare: "recent", threshold: 5, polarity: -1,
        metric: "ICE BofA U.S. high-yield option-adjusted spread (daily → compared recent)",
        what: "How much extra yield investors demand to hold junk-rated corporate bonds versus Treasuries. Wider spreads mean credit markets are nervous.",
        why: "Scout find: high-yield spreads move inversely with consumer-discretionary risk appetite in our sample. Auto buyers (and auto lenders) feel tighter credit when junk spreads blow out — a headwind for Ford's volume and financing arm.",
        up: "credit stress is rising (junk spreads are wider)", down: "credit stress is easing (junk spreads are tighter)" }),
    ],
  },
];

// Illustrative ideas + research notes. Live proxies (when we found free, frequent public data) are wired into curated stocks above.
export const IDEAS = [
  { title: "Recycling volumes → electronics demand", body: "City e-waste tonnage is usually yearly (EPA ADEPT / Facts & Figures). Live proxy now on Amazon: U.S. paperboard mill production (FRED IPN32213N) plus cardboard box prices — packaging volume and price as a stand-in for goods moving through the system. True municipal recycling feeds stay 'ideas' until a free weekly national series appears.", status: "partial", liveOn: "AMZN" },
  { title: "Moth & pest counts → unsold inventory", body: "The warehouse-moth anecdote never had a free national feed. FWS refuge moth inventories (data.gov) are one-off surveys, not a market series. Still an idea — we won't invent numbers.", status: "idea" },
  { title: "Satellite parking-lot counts → store traffic", body: "Commercial vendors (Orbital Insight-style) charge for car counts. Free Sentinel/Landsat revisit is too slow and cloudy for weekly retail traffic, and scraping Google Popular Times violates terms. Still an idea; no honest free substitute yet.", status: "idea" },
  { title: "Fuel storage from satellites → oil inventories", body: "Live now on ExxonMobil: weekly U.S. commercial crude stocks excl. SPR from the EIA (series WCESTUS1) — the official inventory print markets already watch. Satellite tank-farm estimates remain paid; the EIA series is the free, legal version of the same idea.", status: "live", liveOn: "XOM" },
];
